### ISSUE TITLE
I would like to ask the author if it can be compatible with the M chip

### ISSUE THREAD

**Issue by liyuhaolol** [NSAntoine/Samra#17]
I found that this project can only run well on the X86 platform. When I switched to the ARM platform, there was no response after selecting the replacement image. After running the source code, I found that the corresponding method could not be found on the ARM platform. The error is as follows:
```
-[CUIThemeRendition initWithCSIData:forKey:]: unrecognized selector sent to instance 0x600000978000
```
Does the author intend to repair this file and make it compatible with the ARM platform? ?

**Comment by NSAntoine** [comment]
https://github.com/NSAntoine/Samra/releases/tag/1.4.1

**Comment by liyuhaolol** [comment]
> https://github.com/NSAntoine/Samra/releases/tag/1.4.1

Thank you for your reply. I immediately tested your latest submission and found that running your source code with Xcode on M1Pro , Sonoma 14.0 is now working perfectly. However, the 1.4.1 release version you released still cannot edit pictures on M1Pro , Sonoma14.0, and the error situation is the same as the previous version. So feedback to you as a situation. Thank you for your efforts.

**Comment by core-code** [comment]
thanks for adding Apple Silicon compatibility, however this release doesn't work at all on Intel Macs anymore. it is ARM-only:

<img width="389" alt="Screenshot 2024-11-20 at 19 32 52" src="https://github.com/user-attachments/assets/fb8c85ab-548e-4028-bfcf-9764b2e48879">

**Comment by liyuhaolol** [comment]
> thanks for adding Apple Silicon compatibility, however this release doesn't work at all on Intel Macs anymore. it is ARM-only:
> 
> <img alt="Screenshot 2024-11-20 at 19 32 52" width="389" src="https://private-user-images.githubusercontent.com/1261954/388220252-fb8c85ab-548e-4028-bfcf-9764b2e48879.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxNTYxOTIsIm5iZiI6MTczMjE1NTg5MiwicGF0aCI6Ii8xMjYxOTU0LzM4ODIyMDI1Mi1mYjhjODVhYi01NDhlLTQwMjgtYmZjZi05NzY0YjJlNDg4NzkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjFUMDIyNDUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmJhNmMzZDg1YjU1YWEyOTFmODg2MzgzMGRmM2M1NDQ3NTU2ZDc1MDVkZWMzZTg5YzM0ZDEzNTcxYjI2MTkwYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.-xRf_2Esahw4K4-J5eC5_7hYjgqsWm0h8g58qwdpSzM">

Download the source code, compile and run it using XCode. Do not directly download the precompiled program from the author. This should resolve your issue.
